#30 DatasetEditManager unit test
eclipse-che4z/che-che4z-zos-resource-explorer pull request #65
Opened 2019-09-05 20:23 UTC by sergiuilie

2019-09-05 20:24 UTC, sergiuilie commented
@shciubrcom if you squash, do not forget to put the issue ID

2019-09-06 07:30 UTC, shciubrcom requested changes
Seems that some tests miss asserts

2019-09-06 07:30 UTC, shciubrcom commented on src/__mocks__/vscode.ts
> +// tslint:disable-next-line: no-namespace
`// tslint:disable: max-classes-per-file no-namespace` should be reeped and `// tslint:disable-next-line: no-namespace` can be removed

2019-09-06 07:30 UTC, shciubrcom commented on src/__mocks__/vscode.ts
> +// export class EventEmitter {
Commented code should be removed

2019-09-06 13:45 UTC, merged